name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare artifact
        run: |
          mkdir -p out
          # Kopírovat všechny důležité soubory a složky
          cp index.html out/
          cp service-worker.js out/
          cp manifest.webmanifest out/
          
          # Kopírovat složky
          cp -R styles out/
          cp -R engine out/
          cp -R games out/
          
          # GitHub Pages bez Jekyllu
          touch out/.nojekyll
          
          # Pokud v SW existuje __CACHE_VERSION__, nahradíme krátkým SHA
          if grep -q "__CACHE_VERSION__" out/service-worker.js; then
            SHORT_SHA=${GITHUB_SHA::7}
            sed -i "s/__CACHE_VERSION__/$SHORT_SHA/g" out/service-worker.js || true
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4